sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: b+NwsHe+HMZlK78YfIieZBRRbEW/WV10/qa6kfWGyMr8jVwUfKy9kxQAXImWhcqDyrP+FJtfJSMircfUa1sPNqcaa4l3mQkrVR6QOOrWNNvLW75eernk8I8JxqiBuM1lvY6WIZaSjk3s65qiyIl9mUPZ3QuZzfDXm/Iugs3gC9miHQbMkroQ2Wsty2TTgHDy+xVPehGyF8ip650wMeWwqALAGn/GsC1js1/XK9Tt3mmzjG5NsC4sEGvzWH/vT2IyVAOPBW8FpWLraNa6+5cfAEOWFXm5+3rHHk64lqpWIxLe7EHgOr2+JYUI51vFAbRsGmdgMYwV49NKMjScBiVpxSU+bOMhG/kBrRpF1TeJLFGK7fHXAPpLwx0EWbQXl3yk2huMFvlhL8zsdien8H4hqR3aKOGIkefHCnJLXYGpcsFsaIYN39Uhy0Nm/RCxrWwnhc9Hv2r0FwMjQUHEnuAkhO7kBYyMZdsDHrwz8KV8A96GotY8MTjnE3X682Qzc4xQWCXZS7VhDDW4ppUxRsHQydnZL3cbSzU0MpfAfiwpExWAoX0+M+9S1YeR1sqhCx9mBvHIUPNUZzgvVY7npr9pBDT0dxbwu1ALi5dYayfiLAP2s26jF5YftPUaR7eeKwdV0TH7FCYUCldOSf7Lrr55r8ePpDt81rk3JocfJLb14Qk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Princess-Polly-s-Playmates_5426
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy